### ISSUE TITLE
Get PHP-Push-2  CARDDAV working with owncloud 8 ?

### ISSUE THREAD

**Issue by scramatte** [arved/PHP-Push-2-owncloud#11]
Hi,

Does anybody get  PHP-Push-2  CARDDAV working with owncloud 8 ?
I've got mac and iphone and I'm unable to sync contacts.

IMAP and Calendars look to work well

Thank you for your help

**Comment by t3chguy** [comment]
Try https://github.com/fmbiete/Z-Push-contrib

**Comment by scramatte** [comment]
I've just tried it   but  now neither carddav or imap work.
I've got authentication error as my username are email and looks Z-Push-contrib strip domain name.

**Comment by t3chguy** [comment]
That's a config option in the main config.php file

```
    define('USE_FULLEMAIL_FOR_LOGIN', true);
```

**Comment by scramatte** [comment]
Everything works. Thank you very much
