### ISSUE TITLE
multiple Groups a new group will be created on the phone

### ISSUE THREAD

**Issue by arved** [arved/PHP-Push-2-owncloud#2]
I just found another bug: If a contact has multiple Groups a new group will be created on the phone ("Group1,Group2") instead of putting the contact the Group "Group1" and "Group2" separately.

**Comment by magcks** [comment]
In RFC6350 multiple groups are separated by a ",": https://tools.ietf.org/html/rfc6350#section-6.7.1

Probably PHP-Push-2 sends this string to ActiveSync without converting it.

**Comment by magcks** [comment]
Fixed: https://github.com/arved/PHP-Push-2-owncloud/commit/4334f2183aed05895876c1752ab6fe0d8a976408

**Comment by magcks** [comment]
oczpush uses the function "w2ui" everywhere. I currently don't know what it aims. See https://github.com/gza/oczpush/blob/master/backend/occontacts.php#L320

**Comment by arved** [comment]
oczpush has a different apporach, which doesn't fit my needs,  so I didn't took a closer look to the code
