### ISSUE TITLE
var_dump

### ISSUE THREAD

**Issue by magcks** [arved/PHP-Push-2-owncloud#3]
Is the var_dump at carddav.php required or can we remove it?

https://github.com/arved/PHP-Push-2-owncloud/blob/master/backend/carddav.php#L700

**Comment by arved** [comment]
I'll check tomorrow

**Comment by arved** [comment]
this derives from the original code. Can't find out if needed anywhere else.

**Comment by magcks** [comment]
Yeah, I think we can remove it because anywhere else an output buffering should be started. Else it wouldn't make any sense.

**Comment by arved** [comment]
feel free to remove it from the master branch
