### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by magcks** [arved/PHP-Push-2-owncloud#4]
after I've tested again, I found the following errors:
- If I am adding a new group on Android it will be synced with ownCloud successfully. If I then change the contact I have added to this group ownCloud a new group will be created on Android. (--> I think there is a bug on sending the group ID of the group from Android to ownCloud)
- (Creating a new group on ownCloud works fine.)
- If I delete a group on Android it won't be deleted on ownCloud.
- If I delete a group on ownCloud it won't be deleted on Android.

**Comment by arved** [comment]
in this case the vcard groups are converted to activesync categories and again to vcard groups. Though the intend of both features, regarding contacts, is similar, it not the same. Just look at the way categories are used in Outlook. 
And we're depending on how the conversion (i.e. ActiveSync client) on the end user device  is dealing with this.
There is no group sync thingy, but the clients try to catch groups / categories indirect by taking the existing groups for the contacts, and the do some magic with it. 
a group is a property of a vcard that's it. There is no group database which can be synced. How the groups are displayed an how deletions are reflected is completely on the client side.
So from a technial perspective, if you delete a group on one side, a property of all contacts is changed. And that will be synced. If there is no clientsided code, to recognize, that on group is not longer used by all contacts, the group will locally "survive".
