### ISSUE TITLE
Missing letters in Vcard

### ISSUE THREAD

**Issue by stentor142** [arved/PHP-Push-2-owncloud#8]
Hello.
I am experiencing some problems with my Nokia E6-00 and in-built Mail-for-Exchange client when syncing with PHP-Push-2-owncloud & ownCloud 5.0.12.
The problem appears when I create contact through the phone, and then synced to the server. In the field where mail address has to be there are 2 missing letters - first and last.
Eg. kur@abv.bg appears as ur@abv.b --> http://ludmanlandia.net/temp2/php-push2_oc/appearance_in_oc.png
Also, as you can see from the screenshot, name appears "Last name", "First name".
In the phone memory, the name appears as I wish - "First name" "Last name". And the e-mail address is correct too.
When the contact is created through web interface from OC, there is no such problems.
Here is the log from z-push.log http://ludmanlandia.net/temp2/php-push2_oc/z-push.log_upload_to_server

**Comment by arved** [comment]
Hello,
thanks for your feedbeck.
I've just made a little change that shoud solve the issue, regarding the missing characters in the email address.
Please test the changes. If the issue still persists, please set the log level in the config.php to     define('LOGLEVEL', LOGLEVEL_WBXMLSTACK);
So I can see, what the Nokia is exactly sending via ActiveSync

The save order of the contacts can only be set globally for all Useres in the config.php with this switch:
define('FILEAS_ORDER', SYNC_FILEAS_LASTFIRST);
There is another switch CARDDAV_FILEAS_ALLWAYSOVERRIDE_OC5 you may set to false, to disable a forced override

**Comment by stentor142** [comment]
Thank you very much! All is fine now - e-mails, and save order of the contacts. 
I will buy you a beer (or coke) definitely! Cheers from Bulgaria!
