### ISSUE TITLE
request for contrubution access

### ISSUE THREAD

**Issue by nafets227** [arved/PHP-Push-2-owncloud#9]
Hi arved,

may I ask you to give me write Access to the repo, I could commit some changes to make carddav_oc5 more Close to original carddav to ease merging in future.

besides it could help to fullfil the requirements from dupondje about the soure formatting, especially indenting.

**Comment by arved** [comment]
you're added as contributor. hope this fits your demand

**Comment by nafets227** [comment]
Thanks, it works.
